apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: stehedor/finance-backend-image
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/"
        - name: MYSQL_HOST
          value: "mysql-finances"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "financedb"
        - name: MYSQL_USERDB_HOST
          value: "mysql-users"
        - name: MYSQL_USERDB_USER
          value: "root"
        - name: MYSQL_USERDB_PASSWORD
          value: "password"
        - name: MYSQL_USERDB_DATABASE
          value: "userdb"
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000