version: '3.8'

services:
  app-backend:
    build: ./Backend
    container_name: app-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb-service:27017/
      # Mysql finance
      - MYSQL_HOST=mysql-finances
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=financedb
      # Mysql users
      - MYSQL_USERDB_HOST=mysql-users
      - MYSQL_USERDB_USER=root
      - MYSQL_USERDB_PASSWORD=password
      - MYSQL_USERDB_DATABASE=userdb
    depends_on:
      - mongodb
      - mysql-finances 
      - mysql-users
  
  app-frontend:
    build: ./Frontend
    container_name: app-frontend
    ports:
      - "80:80"
    depends_on:
      - app-backend

  mongodb:
    image: mongo:5.0
    container_name: mongodb-service
    environment:
      MONGO_INITDB_DATABASE: financedb
    volumes:
      - mongo-data:/data/db
      - ./volumes/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"

  mysql-finances:
    image: mysql:8.0
    container_name: mysql-finances
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: financedb
    volumes:
      - mysql-data-finances:/var/lib/mysql
      - ./volumes/mysql-finances-init.sql:/docker-entrypoint-initdb.d/mysql-finances-init.sql
    ports:
      - "3306:3306"

  mysql-users:
    image: mysql:8.0
    container_name: mysql-users
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb
    volumes:
      - mysql-data-users:/var/lib/mysql
      - ./volumes/mysql-users-init.sql:/docker-entrypoint-initdb.d/mysql-users-init.sql
    ports:
      - "3307:3306"

  adminer-finances:
    image: adminer:latest
    container_name: adminer-finances
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-finances
    ports:
      - "8080:8080"
    depends_on:
      - mysql-finances

  adminer-users:
    image: adminer:latest
    container_name: adminer-users
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-users
    ports:
      - "8082:8080"
    depends_on:
      - mysql-users

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-service
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app-frontend
  #     - app-backend

volumes:
  mongo-data:
  mysql-data-finances:
  mysql-data-users: