apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-finances-init-config
data:
  mysql-finances-init.sql: |
    -- Crear base de datos si no existe
    CREATE DATABASE IF NOT EXISTS financedb;

    -- Usar la base de datos creada
    USE financedb;

    -- Crear tabla 'finances'
    CREATE TABLE IF NOT EXISTS finances (
        id INT AUTO_INCREMENT PRIMARY KEY,
        date DATE NOT NULL,
        revenue DECIMAL(10, 2) NOT NULL,
        expense DECIMAL(10, 2) NOT NULL
    );

    -- Insertar datos iniciales solo si la tabla 'finances' fue creada
        INSERT INTO finances (date, revenue, expense)
        SELECT '2024-01-01', 5000.00, 3000.00
        WHERE NOT EXISTS (SELECT 1 FROM finances LIMIT 1);
        INSERT INTO finances (date, revenue, expense)
        SELECT '2024-02-01', 6000.00, 4000.00
        WHERE NOT EXISTS (SELECT 1 FROM finances LIMIT 1);
        INSERT INTO finances (date, revenue, expense)
        SELECT '2024-03-01', 7000.00, 4500.00
        WHERE NOT EXISTS (SELECT 1 FROM finances LIMIT 1);
        INSERT INTO finances (date, revenue, expense)
        SELECT '2024-04-01', 8000.00, 5000.00
        WHERE NOT EXISTS (SELECT 1 FROM finances LIMIT 1);
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-users-init-config
data:
  mysql-users-init.sql: |
    -- Crear base de datos para usuarios si no existe
    CREATE DATABASE IF NOT EXISTS userdb;

    -- Usar la base de datos de usuarios
    USE userdb;

    -- Crear tabla 'users'
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    # -- Insertar datos iniciales (usuarios de ejemplo)
    # INSERT INTO users (username, password, email) VALUES
    # ('admin', 'admin_password_hash', 'admin@example.com'),
    # ('user1', 'user1_password_hash', 'user1@example.com');