apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-finances-pvc
spec:
  storageClassName: manual-finances
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-users-pvc
spec:
  storageClassName: manual-users
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi