apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-finance-pv-volume
  labels:
    type: local
spec:
  storageClassName:  manual-finances
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mysql-finance"
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-users-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual-users
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/mysql-users"