services:
  minio:
    image:  minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
    container_name: minio-bucket
    hostname: minioBucket
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
    command: ["server", "/data", "--console-address", ":9001"]   
    


volumes:
  minio-data:

# aws s3api list-buckets --endpoint-url http://localhost:9000 --region us-east-1 --access-key admin --secret-key admin123
